language: python
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

install:
    - sudo apt-get update
    - sudo apt-get install
    - pip install flask selenium requests flask-compress
before_script:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver*.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - FLASK_APP=app.py flask run &

script: python functional_tests.py
